apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
    # app.kubernetes.io/name: webserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
