apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    app: nginx
    # app.kubernetes.io/name: webserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
