apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    # app.kubernetes.io/name: webserver
    app: nginx
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
